version: "3"
services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - kube

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /var/log:/var/log
      - /etc/.minikube:/etc/.minikube
      - /var/lib/docker:/var/lib/docker
    links:
      - "elasticsearch"
    environment:
      - "KUBERNETES_SERVICE_HOST=192.168.49.2"
      - "KUBERNETES_SERVICE_PORT=8443"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - kube

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - kube

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - kube

networks:
  kube:
    driver: bridge
    #external:
    #  name: bridge
